version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/electronicdevices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 17082002
      JWT_SECRET: Ghd73mJ2mX9sR3pQ5L8vY2cS7kE4rT9fW1xQ7hN6bZ3pD2gF4uZ
      JWT_EXPIRATION: 86400000
      REDIS_CHAT_BOX_HOST: redis
      REDIS_CHAT_BOX_PORT: 6379
      SPRING_STATIC_LOCATION: file:///static/
    depends_on:
      - postgres
      - redis
    volumes:
      - /path/to/static:/static

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17082002
      POSTGRES_DB: electronicdevices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
