
version: '3.9'
services:
  master:
    image: postgres:16
    container_name: postgres_master
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./master:/var/lib/postgresql/data

  slave:
    image: postgres:16
    container_name: postgres_slave
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    depends_on:
      - master
    ports:
      - "5433:5432"
    volumes:
      - ./slave:/var/lib/postgresql/data

#  pgpool:
#    image: bitnami/pgpool:4
#    container_name: pgpool
#    environment:
#      - PGPOOL_BACKEND_NODES=0:postgres_master:5432,1:postgres_slave:5433
#      - PGPOOL_SR_CHECK_USER=admin
#      - PGPOOL_SR_CHECK_PASSWORD=1234
#      - PGPOOL_POSTGRES_USERNAME=admin
#      - PGPOOL_POSTGRES_PASSWORD=1234
#      - PGPOOL_ADMIN_USERNAME=pgpool_admin
#      - PGPOOL_ADMIN_PASSWORD=pgpool_password
#      - PGPOOL_FAILOVER_ON_BACKEND_ERROR=yes
##      - PGPOOL_FAILOVER_COMMAND=/opt/bitnami/scripts/pgpool/failover.sh %d %P %H %R
#      - ALLOW_EMPTY_PASSWORD=yes
#
#    ports:
#      - "5434:5432"
#    depends_on:
#      - master
#      - slave
#    volumes:
#      - ./pgpool/conf:/opt/bitnami/pgpool/conf
#      - ./pgpool/scripts/failover.sh:/opt/bitnami/scripts/pgpool/failover.sh

  pgpool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgpool
#    image: bitnami/pgpool:4
#    container_name: pgpool
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres_master:5432,1:postgres_slave:5433
      - PGPOOL_SR_CHECK_USER=admin
      - PGPOOL_SR_CHECK_PASSWORD=1234
      - PGPOOL_POSTGRES_USERNAME=admin
      - PGPOOL_POSTGRES_PASSWORD=1234
      - PGPOOL_ADMIN_USERNAME=pgpool_admin
      - PGPOOL_ADMIN_PASSWORD=pgpool_password
      - PGPOOL_FAILOVER_ON_BACKEND_ERROR=yes
      - PGPOOL_FAILOVER_COMMAND=/opt/bitnami/scripts/pgpool/failover.sh %d %P %H %R
    volumes:
      - ./pgpool/conf:/opt/bitnami/pgpool/conf
      - ./pgpool/scripts/init.sh:/opt/bitnami/scripts/init.sh
      - ./pgpool/scripts/failover.sh:/opt/bitnami/scripts/pgpool/failover.sh
      - ./pgpool/scripts/follow_primary.sh:/opt/bitnami/scripts/pgpool/follow_primary.sh
    entrypoint: [ "/opt/bitnami/scripts/init.sh" ] # chạy scripts để đảm bảo luôn sao chéo config vào /opt/bitnami/pgpool/conf --> Tránh việc image bitnamit/pgpool kiểm tra các tệp cấu hình trong /opt/bitnami/pgpool/conf (trống hoặc thiếu) nó sẽ tạo các têệp câu hình và ghi đè lên container -> host cũng bị ghi đè do đang ánh xạ host - container.
    ports:
      - "5434:5432"
    depends_on:
      - master
      - slave
