
version: '3.9'
services:
  master:
    image: postgres:16
    container_name: postgres_master
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./master:/var/lib/postgresql/data

  slave:
    image: postgres:16
    container_name: postgres_slave
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    depends_on:
      - master
    ports:
      - "5433:5432"
    volumes:
      - ./slave:/var/lib/postgresql/data